---
version: '3'

services:
  nginx:
    image: nginx:1.15.8-alpine
    container_name: yumetasuke_nginx
    ports:
      - ${NGINX_DEVELOPMENT_PORT}:80
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - src_dir:/usr/share/nginx/html

  wordpress:
    image: wordpress:5.0.3-php7.2-fpm-alpine
    container_name: yumetasuke_wordpress
    depends_on:
      - mysql
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: &db-user ${WORDPRESS_DB_USER_NAME}
      WORDPRESS_DB_PASSWORD: &db-password ${WORDPRESS_DB_USER_PASSWORD}
      WORDPRESS_DB_NAME: &db-name ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG_ENABLE}
    volumes:
      - src_dir:/var/www/html

  mysql:
    image: mysql:5.7.24
    container_name: yumetasuke_mysql
    restart: always
    environment:
      MYSQL_DATABASE: *db-name
      MYSQL_USER: *db-user
      MYSQL_PASSWORD: *db-password
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - mysql_data:/var/lib/mysql

  composer:
    image: composer:1.8.0
    container_name: yumetasuke_composer
    restart: always
    volumes:
      - src_dir:/app

  node:
    image: node:10.15.0-alpine
    container_name: yumetasuke_node
    restart: always
    working_dir: /home/node/
    volumes:
      - src_dir:/home/node

volumes:
  mysql_data:
    driver_opts:
      type: none
      device: ${PROJECT_ROOT_PATH}/containers/mysql/data
      o: bind
  src_dir:
    driver_opts:
      type: none
      device: ${PROJECT_ROOT_PATH}/src
      o: bind
